[package]
name = "iron_crawler"
version = "0.1.0"
authors = ["Caleb Webber <caleb.webber@unos.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.amethyst]
version = "0.15.3"
features = ["vulkan"]